var GAME_LEVELS = [
  ["                        e                                                       ",
   "                                                                                ",
   "                                                                            xx  ",
   "                                                                             x  ",
   "                                                                             x  ",
   "                                                                             x  ",
   "                                                                             x  ",
   "                                                                             x  ",
   "                                        o                  o                 x  ",
   "                                                                             x  ",
   "                                               xxxxxxx                       x  ",
   "  xx                                  xxxxx                     xxxxxx       x  ",
   "  x                                                             x    x       x  ",
   "  x                                                             x    x       x  ",
   "  x             o             xxxxx          o                p x    x   f   x  ",
   "  x                                                             x    x       x  ",
   "  x  @                                                          x    x       x  ",
   "  xxxxxxx     xxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        xxx    xxxxxxxxx  ",
   "        x     x   x     x                            x        x                 ",
   "        x!!!!!x   x!!!!!x                            x!!!!!!!!x                 ",
   "        x!!!!!x   x!!!!!x                            x!!!!!!!!x                 ",
   "        xxxxxxx   xxxxxxx                            xxxxxxxxxx                 ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                             w                                    ",
   "                                                                                                                  ",
   "                                                                                       w                          ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                  w                               ",
   "   xx   xx                                                                                                        ",
   "   x     x                                                                                                        ",
   "   x     x                                                                                                        ",
   "   x     x                                                                                                        ",
   "   x     x                                                                                                        ",
   "   x@    x                                                                                                        ",
   "   xx    x                                                                                                        ",
   "   x     x                                                                                                        ",
   "   x    ox                                                                                                        ",
   "   x     x                                                                                                      xx",
   "   x    xx                                                                                                       x",
   "   x     x                            x          xxx                                                             x",
   "   x     x                      xxx   x            x                                                             x",
   "   x     x                        x o x            x                                                             x",
   "   x                              x   x            x                                                             x",
   "   x                              x   x        o   x         o                                                   x",
   "   x                              x o xx           x                                                             x",
   "!!!!!!xxxx              xxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                   x",
   "!!!!!!!!!!!!!xx        ox!!!!!x                      x!!!!!!xx                o    o    o                      f x",
   "!!!!!!!!!!!!!xx         x!!!!!x                    p x!!!!!!xx                                                   x",
   "!!!!!!!!!!!!!xx        xx!!!!!x    o                 x!!!!!!xx           xxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxx",
   "!!!!!!!!!!!!!xx        xx!!!!!xx       xxxxxxxxxxxxxxx!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                          xx  ",
   "                                                                                                           x  ",
   "                                                                         w                                 x  ",
   "                                                                                                           x  ",
   "                                                                                                           x  ",
   "                                                                                                           x  ",
   "                                                                              w                            x  ",
   "                                                                                                           x  ",
   "                                                                                   w                       x  ",
   "                                                                                                  xxx      x  ",
   "  xx                                                            e                                   x      x  ",
   "  x                                                                                                 x      x  ",
   "  x                                                                                                 x      x  ",
   "  x                                                                                                 x      x  ",
   "  x                                                                                            xxx  x      x  ",
   "  x                  r                                                                              x      x  ",
   "  x                                                                                                 x      x  ",
   "  x                                                                                                 x      x  ",
   "  x     r                    o         o                                                            x      x  ",
   "  x                                                                                         xxx     x      x  ",
   "  x           o            xxxx      xxxxx                                                          x      x  ",
   "  x                           x!!!!!!x   x                                                          x      x  ",
   "  x         xxxxx             x!!!!!!x   x                                                          x      x  ",
   "  x         x!!!x             xxxxxxxx p x           o    xxxx                                      x      x  ",
   "  x         x!!!x    xx                  x                   x                           xxx        x      x  ",
   "  x         x!!!x                        x!!!!!!!!!!!x     o x                            ox!!!!!!!!x   f  x  ",
   "  x @       x!!!x                        x!!!!!!!!!!!x       x                             x!!!!!!!!x      x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
